# GitHub Action for running C++ tests using CMake.
# Author: Andrew Jarombek
# Date: 4/30/2023

name: C++ Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  programs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check Out Repository Code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install cmake

      - name: Install Google Test
        run: |
          sudo apt-get install libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/libgtest.a /usr/lib/libgtest.a
          sudo cp lib/libgtest_main.a /usr/lib/libgtest_main.a

      - name: Create Data Alignment build directory
        working-directory: cpp/data-alignment
        run: mkdir build

      - name: Configure CMake for Data Alignment
        working-directory: cpp/data-alignment/build
        run: cmake ..

      - name: Build Data Alignment
        working-directory: cpp/data-alignment/build
        run: cmake --build .

      - name: Run Data Alignment
        working-directory: cpp/data-alignment/build
        run: ./data_alignment

      - name: Create Classes build directory
        working-directory: cpp/classes
        run: mkdir build

      - name: Configure CMake for Classes
        working-directory: cpp/classes/build
        run: cmake ..

      - name: Build Classes
        working-directory: cpp/classes/build
        run: cmake --build .

      - name: Run Classes
        working-directory: cpp/classes/build
        run: ./classes
