# GitHub Action for linting C++ code using clang-tidy.
# Author: Andrew Jarombek
# Date: 11/12/2023

name: C++ Code Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Run Clang-Tidy
        working-directory: cpp
        run: |
          find . -name "*.cpp" -or -name "*.h" | xargs clang-tidy -p=build
